### ISSUE TITLE
Domain name

### ISSUE THREAD

**Issue by ericadamski** [OttawaReactJS/website#2]
Mat and Sopheap are taking the lead on this one 😃

**Comment by matldupont** [comment]
@OttawaReactJS/organizers Do we care to have multiple domains at this point?

The following are all available:

ottawareactjs.ca
ottawareactjs.com
ottawareactjs.co
ottawareactjs.tech
ottawareactjs.online

ottawareactjs.io is also available, but is at a higher price point that I'd have to confirm with Rebel before grabbing.

Opinions?

**Comment by ericadamski** [comment]
Personally I think one is good enough!

My votes 🎟 are `.co` or `.ca`

**Comment by sopheap-hok** [comment]
Some alternatives could be:

ottawareact
reactottawa

Or do we want to be consistent with the name of the meetup group 'ottawareactjs'?

**Comment by ericadamski** [comment]
@sopheap-hok I don't think it has to be consistent :) ottawareact or reactottawa are both great!

**Comment by matldupont** [comment]
I kinda like reactottawa.ca now that I see it in writing

**Comment by matldupont** [comment]
Feels bigger than reactjs

**Comment by ericadamski** [comment]
I am onboard with that :)

**Comment by sopheap-hok** [comment]
OK. I'm making the purchase now.

**Comment by sopheap-hok** [comment]
who's AWS Route53 am I going to set the DNS to?

**Comment by sopheap-hok** [comment]
to be clear, I've acquired 

reactottawa.ca
reactottawa.com

I figure reactottawa.ca will be our main. And we will redirect from .com to the .ca

**Comment by ericadamski** [comment]
AWESOME @sopheap-hok!!!!!
