### ISSUE TITLE
Website returns 404 Page not Found.

### ISSUE THREAD

**Issue by jsivakumaran** [OttawaReactJS/website#22]
![screen shot 2018-10-25 at 8 41 08 pm](https://user-images.githubusercontent.com/10093571/47537914-7128e680-d896-11e8-92b7-c75e49a7be2e.png)

**Comment by jsivakumaran** [comment]
It's only a problem when clicking on the links in the github repo.  Going straight to https://reactottawa.ca/ without the 'www' like it is in the repo works.

**Comment by ericadamski** [comment]
This should be fix now, thank you for submitting an issue! @jsivakumaran
