### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by ericadamski** [OttawaReactJS/website#3]
Any opinions on color schemes? @OttawaReactJS/organizers 

![61dafb-c5fffd-8b8bae-526760-374b4a](https://user-images.githubusercontent.com/6516758/40974735-77236792-6896-11e8-8300-b434e2af207f.png)
![61dafb-cfe8ef-c6dbf0-aed1e6-a0c4e2](https://user-images.githubusercontent.com/6516758/40974736-77380350-6896-11e8-8786-e6d2f5c2c166.png)

**Comment by macdonst** [comment]
@ericadamski never listen to me on design but I prefer the first option as the palette offers better contrast options.

**Comment by ericadamski** [comment]
Inclusion is super important here, so contrast is top of mind! Thanks @macdonst :)

**Comment by matldupont** [comment]
Agreed!

**Comment by sopheap-hok** [comment]
First one, for sure.

**Comment by ericadamski** [comment]
I took the first one and added a better color for text and a simple white
![61dafb-c5fffd-8b8bae-2b303a-ffffff](https://user-images.githubusercontent.com/6516758/41096546-ef1dff18-6a22-11e8-8fa6-cd781e2aad49.png)

This is also close to what I used for the slides

**Comment by matldupont** [comment]
I dig it

**Comment by ericadamski** [comment]
The color pallet above is included in #4
