### ISSUE TITLE
Website Header

### ISSUE THREAD

**Issue by ericadamski** [OttawaReactJS/website#6]
Header as per @matldupont design

![website design](https://user-images.githubusercontent.com/3803431/41267166-5563e74e-6dc8-11e8-81dd-002f58042106.png)

**Comment by matldupont** [comment]
I kind of leveraged the slogan quite a bit for this design, which I thought was a cool take on this kind of meetup.  Do you think the @ReactOttawa tag is prominent enough or should there be more emphasis on ReactJS here?

**Comment by ericadamski** [comment]
I think there is a good balance! When I actually code it tomorrow I'll put up a few variations to see which you like best. 

Should I just pick a place holder image for now or do you have that one you used for the mock up?

**Comment by matldupont** [comment]
![ottawa jpg 1920x1080 2x](https://user-images.githubusercontent.com/3803431/41567694-7a0a841a-732f-11e8-9414-e82c72e490e2.jpg)

**Comment by ericadamski** [comment]
Love that photo!

**Comment by matldupont** [comment]
The opacity I have for the overlay on the mockup is about 65%

**Comment by matldupont** [comment]
Yeah!  It's pretty slick!

**Comment by ericadamski** [comment]
@macdonst what do we think about this?

![screenshot-2018-6-20 ottawa react](https://user-images.githubusercontent.com/6516758/41655828-231668c6-745c-11e8-8a66-ae1e6364fa37.png)
